### ISSUE TITLE
Automatic Disable Navigation if Number of items are not greater than specified

### ISSUE THREAD

**Issue by satish-ambab** [smashingboxes/OwlCarousel2#1018] opened 2015-08-31 10:50 UTC
Automatic Disable Navigation if Number of items are not greater than specified

**Comment by greg5green** [comment] 2015-08-31 13:55
This is a dupe of #967.
>In beta 3, this is "fixed" -- we only display nav and dots if there is somewhere to navigate to. This behavior will hopefully be changing in the future to always show if you pass nav: true, but maintain the old functionality with nav: 'auto' or some similar syntax

[test case](http://codepen.io/anon/pen/OVeypr)

**Closed by greg5green** 2015-08-31 13:55 UTC
