### ISSUE TITLE
"to.owl.carousel" causes error

### ISSUE THREAD

**Issue by thany** [smashingboxes/OwlCarousel2#961] opened 2015-07-31 12:42 UTC
I'm triggering the `to.owl.carousel` event as follows:
```
owl.trigger("to.owl.carousel", [ 0 ]);
```
Where `owl` is a jQuery object to the carousel, I hope that's obvious. Above call will produce an error:
```
TypeError: this._pages[(((position % length) + length) % length)] is undefined
http://localhost/includes/js/owl.carousel.js
Line 2935
```
When I pass a second argument (`speed`) and a third (`default`), it works fine, but since I have no access to the current options (or settings?...) object, I have no way of knowing what to pass. 

**Update**: after some more fiddling, I found that any number for the second argument will produce the same error, and anything other than `true` for the third argument will produce the same error as well
So this is the required call:
```
owl.trigger("to.owl.carousel", [ 0, false, true ]);
```
Where the second and third arguments can't ever be anything else, or so it seems. Odd.

This is with owlCarousel 2.0.0-beta.3, jQuery 2.1.4, and Firefox 39.

**Comment by apermo** [comment] 2015-08-03 06:01
I second that.

I'm using beta 4 with jQuery 1.11.0 in the latest chrome.

I did some debugging and found that this._pages is an empty array. Obviously the function Navigation.prototype.update in lines 2811-2837 somehow malfunctions.

**Comment by greg5green** [comment] 2015-08-19 20:53
I'm not seeing any problems in Firefox 39.0.3 or Chrome 44.0.2403.155 with jQuery 1.10.0, 2.1.3 or 2.1.4 in beta 3.

I've made a [test case](http://codepen.io/anon/pen/MwMKWp) for this -- any chance so it will actually error? Thanks.

**Comment by greg5green** [comment] 2015-08-20 02:27
Ah, figured out how to trigger this error -- `dots: false` will do it every time. Closing since it's a dupe of #448

**Closed by greg5green** 2015-08-20 02:27 UTC
Labels: question
