### ISSUE TITLE
Destroy is not complete

### ISSUE THREAD

**Issue by kjfranke** [smashingboxes/OwlCarousel2#990] opened 2015-08-18 09:27 UTC
Destroy needs an extra unwrap on line 1557
On resize it generates errors on 623 to fix it i put this line in an if statement: if(this.e){

Added an .removeClass('owl-loaded') on line 1554

**Comment by greg5green** [comment] 2015-08-19 14:29
This is a dupe of #404, #485, and #952 and is fixed in beta 3.

**Closed by greg5green** 2015-08-19 14:29 UTC

**Comment by arodger3** [comment] 2016-06-16 16:33
It doesnt work in beta 4
