### ISSUE TITLE
Trigger 'to.owl.carousel' does not work when...

### ISSUE THREAD

**Issue by aguilar-copan** [smashingboxes/OwlCarousel2#714] opened 2015-02-22 20:41 UTC
This event can not be triggered when "dots" option is false

**Comment by seangates** [comment] 2015-05-28 06:11
:+1: for this. I was able to fix the carousel, but I have to hide the dots in CSS. Please fix!

**Comment by mirrur** [comment] 2015-06-01 04:01
:+1:

**Comment by greg5green** [comment] 2015-08-20 03:32
This is a dupe of #448

**Closed by greg5green** 2015-08-20 03:32 UTC
