### ISSUE TITLE
error  this._pages[(((b % e) + e) % e)] is undefined

### ISSUE THREAD

**Issue by dpotuznik** [smashingboxes/OwlCarousel2#795] opened 2015-04-15 16:25 UTC
hi,
sorry i'm new on gitHup i am not sure if is on right place to post.

thank for your plugins, i have an issue i have this error when i try to click on the thumb : this._pages[(((b % e) + e) % e)] is undefined

i found the problem i replace 
this.owl.to(index, options.dotsSpeed);
by
this.owl.to(index, options.dotsSpeed,true);

Hope is help :)
Have nice day
Daniel

**Comment by iclukas** [comment] 2015-07-15 17:30
I can confirm this error. It also happens when a **to.owl.carousel** event is triggered and option **dots** is set to **false**.

**Comment by greg5green** [comment] 2015-08-20 02:27
Confirmed as dupe of #448, closing.

**Closed by greg5green** 2015-08-20 02:27 UTC
