### ISSUE TITLE
A different animateOut classname for owl-next and owl-prev

### ISSUE THREAD

**Issue by gabfire** [smashingboxes/OwlCarousel2#911] opened 2015-07-01 12:38 UTC
Thank you very much for the awesome script.
CSS3 animations are great. It would have been just perfect if we could use a different CSS3 effects for both owl-next and owl-prev functions.

That way when using fadeOutLeft for owl-next, we could use fadeOutRight for owl-prev and have slide items to slide out correct direction of the screen.

**Comment by greg5green** [comment] 2015-08-20 15:46
I'm going to close this as being a duplicate of #958.

**Closed by greg5green** 2015-08-20 15:46 UTC
Labels: feature request
