### ISSUE TITLE
how to go to specific slide

### ISSUE THREAD

**Issue by edelworksgithub** [smashingboxes/OwlCarousel2#785] opened 2015-04-11 09:09 UTC
Please help me out!
Everything worked when I was using v1
Now I am using v2 beta.
$('.step-contents').owlCarousel({
			items : 1,
			dots: false,
			autoHeight : true,
			singleItem : true,
			//autoplay
			touchDrag : false,
			mouseDrag : false,
			autoPlay : false,
			//Transitions
			//transitionStyle : "scaleUp"
			});
var owl_carousel = $(".step-contents").data('owlCarousel');
$(document).on('click','.step-2',function(){
			
		 	owl.goTo(1); // this is not working
			owl_carousel.trigger('to.owl.carousel', [1]);
			//this too is not working
		 });
when is use 
$('.step-contents')..trigger('to.owl.carousel', [1]);
TypeError: this._pages[(((b % e) + e) % e)] is undefined
is throwing

**Comment by remik** [comment] 2015-04-16 01:28
Try:
```
$('.step-contents').trigger('to.owl.carousel', 1);
```

**Comment by seangates** [comment] 2015-05-28 06:09
I get the same thing as @edelworksgithub above.

> Uncaught TypeError: Cannot read property 'start' of undefined

At the same code block, essentially.

**Comment by hentaibbc** [comment] 2015-06-02 10:52
Try to set 'dots' property to true, or set 'slideBy' property to 'page'.

**Comment by greg5green** [comment] 2015-08-20 02:41
There is a bug with `dots: false` and the `to.owl.carousel` event. This is a dupe of #448

**Closed by greg5green** 2015-08-20 02:41 UTC

**Comment by Meomari** [comment] 2018-05-09 14:18
- [ ] 

-1.
