### ISSUE TITLE
Data source support (json, yaml, md?)

### ISSUE THREAD

**Issue by Scottien** [smashingboxes/OwlCarousel2#579] opened 2014-10-29 12:06 UTC
Just wondered why json support was removed?

I used this before as I had quite a large amount of text content on slides which made simple separating this from code. Is it possible that some sort of replacement is in the works or is this lost for good?

**Comment by joeyjoejoejr** [comment] 2015-02-13 22:03
Duplicate of #560

**Closed by joeyjoejoejr** 2015-02-13 22:03 UTC
