### ISSUE TITLE
changed event on input defocus

### ISSUE THREAD

**Issue by ParallelUniv3rse** [smashingboxes/OwlCarousel2#1012] opened 2015-08-27 14:50 UTC
The carousel is throwing an error "Cannot read property name of undefined" from line 2346. 
The changed event is firing when input in carousel loses focus and does not have the data in the event which it "needs".

'change.owl.carousel': $.proxy(function(e) {
	if (e.property.name == 'position') {
          ....

the "property" in "e" object is missing.
 
edit: 
line 2686 is the same story.

**Comment by greg5green** [comment] 2015-08-27 15:02
Can you please come up with a test case as described at https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports? Thanks

**Comment by ParallelUniv3rse** [comment] 2015-09-06 20:18
Can somebody reopen this please? 
Here is a working codepen with basic setup and issue occuring as described. 
change the input's value and defocus it. -> throws an error in the console.

Thank you.

**Comment by joeyjoejoejr** [comment] 2015-09-06 21:01
@greg5green This is verified, and we've seen it on some projects at SB.  It doesn't seem to break anything as far as I can tell, but it might be nice to look into at some point.

**Comment by greg5green** [comment] 2015-09-06 21:32
This is a dupe of #152 and was fixed in 99d493e23517945b45b83239a4b0c8625101cec4.

[Updated test case](http://codepen.io/anon/pen/avObBP)

**Comment by greg5green** [comment] 2015-09-06 21:33
@ParallelUniv3rse The newest version is available on bower and you can get it at http://smashingboxes.github.io/OwlCarousel2/.

**Closed by greg5green** 2015-09-06 21:32 UTC

**Comment by joeyjoejoejr** [comment] 2015-09-06 22:03
My bad.

**Comment by koichirose** [comment] 2016-01-28 08:27
Hmm. Someone should write something here about this new version:
http://www.owlcarousel.owlgraphic.com/
