### ISSUE TITLE
navRewind is not working on beta 2.4

### ISSUE THREAD

**Issue by carlosnpz** [smashingboxes/OwlCarousel2#980] opened 2015-08-11 23:28 UTC
I'm using Owl Carousel beta 2.4, but it's not rewinding as it reaches the last slide. That's my code:

```javascript
var owl1 = $("#carousel1");

	owl1.owlCarousel({
		items: 1,
		dots: false,
        navRewind: true,
		responsive:{
		    0:{
		        nav:false
		    },
		    768:{
		        nav:true,
		        navRewind: true,
				navText: ['<a class="fa fa-chevron-left" href="javascript:;"></a>','<a class="fa fa-chevron-right" href="javascript:;"></a>'],
				navContainer: '#carousel1'
		    },
		    992:{
		        nav:true,
		        navRewind: true,
				navText: ['<a class="fa fa-chevron-left" href="javascript:;"></a>','<a class="fa fa-chevron-right" href="javascript:;"></a>'],
				navContainer: '#carousel1'

		    },
		    1200:{
		    	nav:true,
		        navRewind: true,
				navText: ['<a class="fa fa-chevron-left" href="javascript:;"></a>','<a class="fa fa-chevron-right" href="javascript:;"></a>'],
				navContainer: '#carousel1'
		    }
		}
	});

**Comment by cjbottaro** [comment] 2015-08-15 00:06
Same here.

**Comment by carlosnpz** [comment] 2015-08-15 00:09
Found a weird solution: set the parameter slideBy to 'page'. E.g. slideBy : 'page'

**Comment by cjbottaro** [comment] 2015-08-15 00:44
Awesome, thanks, that worked.

**Comment by greg5green** [comment] 2015-08-15 00:49
What about with beta 3?

**Comment by carlosnpz** [comment] 2015-08-15 01:22
Did you try the same thing?

**Comment by greg5green** [comment] 2015-08-15 03:01
No, I didn't -- this was just (and too subtle) my nice way of telling you that I thought this was fixed in beta 3 which has been out since June :)

I set up a test case and confirmed that it is fixed, so I'm going to close this. You can get the newest version from Bower or from the website -- http://smashingboxes.github.io/OwlCarousel2/ (we're working on getting the other one pointed to this domain)

Two important note for when you upgrade to beta 3:
1. You need to include the `owl-theme` class on your carousel (or write your own css for how you want things to look, which you might already have done since you have the custom chevrons)
2. The `navRewind` property was renamed to be `rewind` so you will need to change that in your script in all four places.

Let me know if you have any other questions.

**Closed by greg5green** 2015-08-15 03:01 UTC
