### ISSUE TITLE
callback is not working 

### ISSUE THREAD

**Issue by phuyem** [smashingboxes/OwlCarousel2#567] opened 2014-10-21 22:10 UTC
owl.owlCarousel({
        items : 3,
        lazyLoad : true,
        loop:true,
        nav : true,
        navText	: ["<",">"],
         onDragged: function(event) {
		     
		}      
      });

event is undefined.

I found a work-around: in Owl.prototype.trigger, change apply() to call() or  simply 

     this.settings[handler] (this, event);

**Comment by joeyjoejoejr** [comment] 2015-02-13 21:49
Looks like a duplicate of this issue: #526

**Closed by joeyjoejoejr** 2015-02-13 21:49 UTC
