### ISSUE TITLE
Dot selection calculations incorrect

### ISSUE THREAD

**Issue by alistairstead3408** [smashingboxes/OwlCarousel2#860] opened 2015-06-02 10:10 UTC
When the number of total items is not divisible by the number of items shown, the selected dot is incorrect. 

In this example, https://jsfiddle.net/alistairstead3408/vxsfk0Lu/, I would expect on clicking the third dot, for it to become selected. I would expect the second dot to take you to [3, 4, 5] rather than [4, 5, 6]. 

Thanks,

**Comment by alistairstead3408** [comment] 2015-06-02 12:10
Also, navRewind, which is set to true by default does not work in this example.

**Comment by greg5green** [comment] 2015-06-19 20:42
I'm noticing this issue in your JSFiddle, but haven't yet been able to replicate it outside of there. Do you have any more info about this issue?

**Comment by greg5green** [comment] 2015-06-21 02:00
@alistairstead3408 I think this is a dupe of #189 and #707 (and maybe others) that was fixed via #231 and is in the newest beta release that you can get if you grab it off Bower or [here, in zip form](http://smashingboxes.github.io/download/owl.carousel.2.0.0-beta.3.zip)

If you still have issues, please reopen the issue! Thanks

**Closed by greg5green** 2015-06-21 02:00 UTC
Labels: task

**Comment by FrankPrendergast** [comment] 2015-06-28 01:18
Apologies if I'm missing something here, but I'm also having trouble with dots when the number of total items is not divisible by the number of items shown.

I have 17 items and 5 showing. When you click on the last dot you go to the end but the second last dot shows as active (not the last dot). I think this is confusing to users who could think they are failing to get to the last items. 

I read through issue 189 which led me here - but the link above to newest Beta release didn't work and the current download from site (owl.carousel.2.0.0-beta.2-1.4) doesn't appear to have fixed it. 

If there is a release that may have fixed this I would love to get my hands on it. Many thanks.

**Comment by greg5green** [comment] 2015-06-28 01:48
I'm sorry, I put a bad URL here! [Correct, working URL](http://smashingboxes.github.io/OwlCarousel2/download/owl.carousel.2.0.0-beta.3.zip)

**Comment by FrankPrendergast** [comment] 2015-06-28 03:08
Thank you so much for the speedy reply - that seems to have fixed my issue with the dots. Many thanks.
