### ISSUE TITLE
dots disappear...

### ISSUE THREAD

**Issue by klausgao** [smashingboxes/OwlCarousel2#1007] opened 2015-08-25 09:16 UTC
version beta3, dots won't show. but using beta2.4's css files with beta3's js file, it works

**Comment by barry205** [comment] 2015-08-25 11:20
I think some css is missing. I had the same issue and found https://github.com/smashingboxes/OwlCarousel2/issues/480 which solved it for me.

**Comment by greg5green** [comment] 2015-08-25 14:01
I think this is a dupe of #892. With beta 3, you need to have a class of `owl-theme` on your carousel if you want the default styling of dots and navigation.

If this does not fix your issue, please submit a bug report as described in https://github.com/smashingboxes/OwlCarousel2/blob/develop/CONTRIBUTING.md#bug-reports and I'll re-open the issue.

**Closed by greg5green** 2015-08-25 14:01 UTC

**Comment by klausgao** [comment] 2015-08-26 01:33
thx guys, it is back O(∩_∩)O~
