### ISSUE TITLE
Blank/flash image on loop

### ISSUE THREAD

**Issue by sandrellix** [smashingboxes/OwlCarousel2#599] opened 2014-11-11 21:52 UTC
Hi,
I have a problem with version 2.0.
I am using this version because I needed to get a continued loop, always from right  to the left.
I almost got it, but in the second loop, between first and second slide there is a blank/flash.

Can somebody help me?

Thanks !
Sandra

**Comment by clarklab** [comment] 2015-01-13 17:06
awesome, that fix from @luminairre worked perfectly for me. Here's a Codepen is anyone wants to play along: http://codepen.io/clarklab/pen/ByWjxy

If you remove those webkit rules, you'll see the flicker during loop

**Comment by jhongstore** [comment] 2015-01-13 17:06
NAVER - http://www.naver.com/
--------------------------------------------

dcjae@naver.com 님께 보내신 메일 <Re: [OwlCarousel2] Blank/flash image on loop (#599)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by malinky** [comment] 2015-01-29 11:09
Thanks luminairre for the fix, pleased to get it sorted so quickly

**Comment by judewang** [comment] 2015-02-12 13:41
Thanks luminairre for fixing, you saved my weekend. :+1:

**Comment by joeyjoejoejr** [comment] 2015-02-14 12:37
Closing as a duplicate of #561

**Closed by joeyjoejoejr** 2015-02-14 12:37 UTC

**Comment by nyala1** [comment] 2015-05-23 23:39
Adding

 -webkit-transform: translateZ(0) scale(1.0, 1.0);

Worked for me
Thanks Luminairre!

**Comment by AndreGoncalvesVC** [comment] 2015-06-01 09:50
Luminairre (Y) !!

**Comment by richyumul** [comment] 2015-06-26 00:29
Bummer.  I feel left out - Luminairre's solution did not work form me. 

Chrome Version 43.0.2357.130 (64-bit)

**Comment by July-** [comment] 2015-07-28 06:42
luminairre! Thanks!

**Comment by dharatank** [comment] 2015-07-28 13:30
hi...I'm using owl carousel slider and facing jumping issue...I tried that -webkit-transform but still facing the same issue....!! plz give me some solution....

**Comment by judewang** [comment] 2015-07-29 02:21
@dharatank have you added this, yet?
```
.owl-item {
        -webkit-backface-visibility: hidden;
        -webkit-transform: translateZ(0) scale(1.0, 1.0);
}
```

**Comment by pootato** [comment] 2015-09-11 18:36
WHY ISN'T THIS FIX ADDED TO THE CODE YET??

**Comment by pootato** [comment] 2015-09-11 18:37
WHY ISN'T THIS FIX ADDED TO THE MASTER CODE YET?? @witrin @OwlFonk
